{
 "title": "Palworld",
 "description": "A Palworld dedicated server dashboard for metrics exported by https://github.com/smbonn2005/palworld-exporter.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Instant Reference", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Players",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "palworld_player_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Level.sav File Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "palworld_level_save_size_bytes / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Player Save Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "palworld_player_save_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Server FPS",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "palworld_server_fps", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Server Frame Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "palworld_server_frametime_milliseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "palworld_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "In-Game Day",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "palworld_world_days", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max Players",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "palworld_player_max", "legendFormat": "__auto" }
   ]
  },
  { "title": "Data over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Server Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "palworld_server_info",
     "legendFormat": "{{name}} ({{instance}}) ({{version}})"
    }
   ]
  },
  {
   "title": "5+ Day Old Player Saves",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(palworld_player_save_mtime < timestamp(palworld_player_save_mtime) - 432000) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporter Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "palworld_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Player Save Last Modifications",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "palworld_player_save_mtime * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Player Save File Sizes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(palworld_player_save_size_bytes / 1000000)",
     "legendFormat": "PlayerUID:{{player_uid}}"
    }
   ]
  },
  {
   "title": "Player Save Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "palworld_player_save_size_bytes / 1000000",
     "legendFormat": "{{player_uid}}"
    }
   ]
  },
  {
   "title": "Active Players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "palworld_player_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Level.sav File Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "palworld_level_save_size_bytes / 1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Players",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    { "expr": "palworld_player", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Server FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "palworld_server_fps", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Server Frame Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "palworld_server_frametime_milliseconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server Uptime (drops indicate restarts)",
   "type": "timeseries",
   "description": "A drop in this line indicates the server process restarted.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    { "expr": "palworld_uptime_seconds", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}